---
title: "dashboard sample"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
params: 
  rate: 2
---
    

```{r setup, include=FALSE}
library(flexdashboard)
library(formattable)
```


# page 1

## col

### value1
```{r}
valueBox(10, 
         caption ="this is caption test",
         color = "info")
```

### value2

```{r}
valueBox(params$rate,caption = "parameter")
```


### value3

```{r}
valueBox(10)
```


## col
  
### Contact Rate

```{r}
gauge(params$rate, 
  min = 0, max = 100, 
  symbol = '%', 
  gaugeSectors(
    success = c(80, 100), 
    warning = c(40, 79), 
    danger = c(0, 39)
))
```

### Average Rating 

```{r}
rating <- 25
gauge(rating, 
      min = 0, max = 50,
      label = "this is label", 
      gaugeSectors(
        success = c(41, 50), 
        warning = c(21, 40), 
        danger = c(0, 20)
))
```

### Cancellations

```{r}
cancellations <- 8
gauge(cancellations, min = 0, max = 10, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

# page 2

## col

### box1

### box2

## col {.tabset}

### box3

### box4

### box5