---
title: "jsgadget samples"
author: "Jun Ohashi"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    code_folding: hide
    self_contained: true
    thumbnails: false
    lightbox: false
    md_extensions: -ascii_identifiers
    css: template.css
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

library(plotly)
library(dygraphs)
library(metricsgraphics)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
                 cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
```

# plotly


# formattable

# metricsgraphics

基本シンタックスはmjs_xxx、All plots begin with mjs_plot　　
mjs_plot(x=,y=) %>%   

+ mjs_bar()
+ mjs_line() → mjs_add_line()
+ mjs_histogram(bar_margin=, )
+ mjs_point(color_accessor=, size_accessor=)

プロット以外  

+ mjs_labs(x="Weight of Car", y="Miles per Gallon")
+ mjs_add_marker()
+ mjs_add_baseline()
+ mjs_add_legend(legend=c("X", "Y", "Z"))

グリッド  

+ mjs_grid(p1, p2, ncol=2)

```{r}
tmp <- data.frame(year=seq(1790, 1970, 10), uspop=as.numeric(uspop))

tmp %>%
  mjs_plot(x=year, y=uspop) %>%
  mjs_line() %>%
  mjs_add_marker(1850, "Something Wonderful") %>%
  mjs_add_baseline(150, "Something Awful")


tmp %>%
  mjs_plot(x=uspop, y=year, width=500, height=400) %>%
  mjs_bar() %>%
  mjs_axis_x(xax_format = 'plain')
```


```{r}
stocks <- data.frame(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4))

stocks %>%
  mjs_plot(x=time, y=X) %>%
  mjs_line() %>%
  mjs_add_line(Y) %>%
  mjs_add_line(Z) %>%
  mjs_axis_x(xax_format="date") %>%
  mjs_add_legend(legend=c("X", "Y", "Z"))
```

```{r}
mtcars %>%
  mjs_plot(x=wt, y=mpg, width=600, height=500) %>%
  mjs_point(color_accessor=carb, size_accessor=carb) %>%
  mjs_labs(x="Weight of Car", y="Miles per Gallon")
```


# dygraphs
time series